---
ansible_host: 10.0.160.3
DOCKER: dockerd160
mac: "02:42:0a:00:a0:03"
hostname: alephone
fqdn: alephone.example.com
rootable: 0 # 1 for yes
difficulty: 0
#scheduled_at: "YYYY-mm-dd HH:MM:SS"
container:
  name: "{{hostname}}"
  hostname: "{{fqdn}}"
  build: "alephone" # The current folder name
  image: "alephone" # The current folder name
  state: "started"
  mac_address: "{{mac}}"
  purge_networks: "yes"
#  tag: "v0.1"
#  buildargs:
#   var_name: var_value
  env:
    ETSCTF_FLAG: "ETSCTF_{{ETSCTF_ENV_FLAG}}"
  dns_servers:
    - "8.8.8.8"
  networks:
    - { name: echoctfred_targets, ipv4_address: "{{ansible_host}}" }
  volumes: []

ETSCTF_ROOT_FLAG: "ETSCTF_ROOT_FLAG"
ETSCTF_ENV_FLAG: "ETSCTF_ENV_FLAG"
ETSCTF_SHADOW_FLAG: "ETSCTF_SHADOW_FLAG"
ETSCTF_PASSWD_FLAG: "ETSCTF_PASSWD_FLAG"
envstr:  "ETSCTF_FLAG=ETSCTF_{{ETSCTF_ENV_FLAG}}\n"
envhash:  "{{envstr|hash('sha256')}}"


ETSCTF_FINDINGS:
  - {
      name: "Discovered target host {{fqdn}}/{{ansible_host}}",
      pubname: "Discovered a target host",
      points: 100,
      stock: -1,
      protocol: "icmp",
      port: 0
    }
  - {
      # Message that will be displayed on the users private activity stream
      name: "Discovered the 666/tcp service on target {{fqdn}}",
      # Message that will be displayed on the public activity stream
      pubname: "Discovered a service",
      points: 100,
      stock: -1,
      protocol: "tcp",
      port: 666
    }

ETSCTF_TREASURES:
  - { #0
      name: "Got the ETSCTF flag under the /root folder of {{fqdn}}",
      pubname: "Got the ETSCTF flag under the /root folder of {{fqdn}}",
      points: 1500,
      player_type: offense,
      stock: -1,
      code: "{{ETSCTF_ROOT_FLAG}}",
      path: "/root/ETSCTF_"
    }
  - { #1
      name: "Discovered the environment variable ETSCTF flag of {{fqdn}}",
      pubname: "Gained access to data stored in environmental variables of a server",
      points: 900,
      player_type: offense,
      stock: -1,
      code: "{{ETSCTF_ENV_FLAG}}",
    }
  - { #2
      comment: "flag on /etc/shadow",
      name: "Discovered the ETSCTF username flag under the /etc/shadow file of {{fqdn}}",
      pubname: "Discovered the ETSCTF username flag under an authentication database file of a server",
      points: 1300,
      player_type: offense,
      stock: -1,
      code: "{{ETSCTF_SHADOW_FLAG}}",
    }
  - { #3
      comment: "flag on /etc/passwd",
      name: "Discovered the ETSCTF username gecos flag under the /etc/passwd file of {{fqdn}}",
      pubname: "Discovered the ETSCTF flag on gecos details of a target",
      points: 1300,
      player_type: offense,
      stock: -1,
      code: "{{ETSCTF_PASSWD_FLAG}}",
    }
  - {
      name: "Discovered the ETSCTF flag from the vulnerable.c variable of {{fqdn}}",
      pubname: "Discovered an ETSCTF flag on a vulnerable application",
      points: 100,
      player_type: offense,
      stock: -1,
      code: "THIS_IS_MY_EXAMPLE_ETSCTF_FLAG",
      replace: "EXAMPLE_FLAG_PLACEHOLDER",
      file: "/usr/src/vulnerable.c",
    }
# These commands are executed at build time by ansible
BUILD_COMMANDS:
  exec:
  - { cmd: "gcc -o /usr/local/bin/vulnerable /usr/src/vulnerable.c" }
  replace:
  - { #0
      pattern: "EXAMPLE_REPLACE_PLACEHOLDER",
      file: "/usr/src/vulnerable.c",
      value: "This was compiled for {{fqdn}}",
    }
  - { #1
      pattern: "ENVFLAG_HASH",
      file: "/usr/local/sbin/healthcheck.sh",
      value: "{{envhash}}",
    }
DETAILS:
  - { username: "ETSCTF", password: "ETSCTF_{{ETSCTF_SHADOW_FLAG}}", gecos: "ETSCTF_{{ETSCTF_PASSWD_FLAG}}", group: "nogroup", module: 'user' }


purpose: >
  A short text describing the purpose of the target

description: >
  description for the target
