site_name: echoCTF.RED Documentation
site_url:  https://echoctfred.readthedocs.io/en/latest/
site_description: A framework for developing, deploying, running and maintain CTFs
repo_url: https://github.com/echoCTF/echoCTF.RED
theme: readthedocs

pages:
  - Home: README.md
  - Architecture: docs/ARCHITECTURE.md
  - Getting Started: docs/README.md
  - Installation:
    - Using Docker Compose:
      - All in one host: /docs/DOCKER-COMPOSE.md
      - All in one with separate VPN: /docs/DOCKER-COMPOSE-NOVPN.md
    - Manual installation:
      - OpenBSD General installation instructions of applications: /docs/INSTALL.md
      - Manual installation of all application on a single linux host: /docs/INSTALL-LINUX.md
      - Build echoCTF.RED applications Docker images: /docs/BUILD-DOCKER.md
    - Extras:
      - Install VPN Gateway on OpenBSD: /docs/VPN-SERVER.md
      - Setup a Private Docker Registry: /docs/DOCKER-REGISTRY.md
      - Docker Servers Setup Guide: /docs/DOCKER-SERVERS.md
      - Docker Targets Guide: /docs/DOCKER-TARGETS.md
      - Personalize your installation: /docs/PESONALIZING.md
  - Administration:
      - Sysconfig Keys: docs/Sysconfig-Keys.md
      - Console Commands: docs/Console-Commands.md
