site_name: echoCTF.RED Documentation
site_url:  https://echoctfred.readthedocs.io/en/latest/
site_description: A framework for developing, deploying, running and maintain CTFs
repo_url: https://github.com/echoCTF/echoCTF.RED
theme: readthedocs

pages:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Sizing: Infrastructure-Sizing.md
  - Getting Started: Getting-Started.md
  - Install using docker-compose:
    - All in one host: DOCKER-COMPOSE.md
    - All in one with separate VPN: DOCKER-COMPOSE-NOVPN.md
  - Manual installation:
    - OpenBSD General installation instructions of applications: INSTALL.md
    - Manual installation of all application on a single linux host: INSTALL-LINUX.md
  - Extras:
    - Install VPN Gateway on OpenBSD: VPN-SERVER.md
    - Setup a Private Docker Registry: DOCKER-REGISTRY.md
    - Docker Servers Setup Guide: DOCKER-SERVERS.md
    - Docker Targets Guide: DOCKER-TARGETS.md
    - Personalize your installation: PERSONALIZING.md
  - Administration:
      - Sysconfig Keys: Sysconfig-Keys.md
      - Console Commands: Console-Commands.md
