build:
    environment:
        php: 7.3.0
    nodes:
        frontend:
            root_path: "./frontend"
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis --sub-project-dir=frontend/
                    -
                      command: phpcs-run
                      idle_timeout: 1200
        backend:
            root_path: "./backend"
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis --sub-project-dir=backend/
                    -
                      command: phpcs-run
                      idle_timeout: 1200

        tests: true
    dependencies:
        before:
            - composer global require "fxp/composer-asset-plugin" --no-interaction
filter:
  dependency_paths:
    - "*/vendor/"
checks:
  php:
    code_rating: true
    duplication: true
    fix_php_opening_tag: false
    remove_php_closing_tag: false
    one_class_per_file: false
    side_effects_or_types: false
    no_mixed_inline_html: false
    require_braces_around_control_structures: false
    php5_style_constructor: false
    no_global_keyword: false
    avoid_usage_of_logical_operators: false
    psr2_class_declaration: false
    no_underscore_prefix_in_properties: false
    no_underscore_prefix_in_methods: false
    blank_line_after_namespace_declaration: false
    single_namespace_per_use: false
    psr2_switch_declaration: false
    psr2_control_structure_declaration: false
    avoid_superglobals: false
    security_vulnerabilities: true
    no_exit: false

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 2
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            if:
                opening: new-line
                always: false
                else_on_new_line: true
            for:
                opening: new-line
                always: false
            while:
                opening: undefined
                always: false
            do_while:
                opening: undefined
                always: false
                while_on_new_line: false
            switch:
                opening: undefined
            try:
                opening: new-line
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: undefined
            constants:
                true_false_null: undefined
