---
- name: Submit challenges to mUI
  hosts: localhost
  connection: local
  serial: 1
  vars:
    mui:
      URL: http://localhost:8080
  tasks:
  - name: "Processing Given challenge"
    when: CHALLENGE_YML is defined
    include: _challenge.yml
    vars:
      challenge_yml: "{{CHALLENGE_YML}}"


  - name: "Processing challenges/*.yml"
    when: CHALLENGE_YML is not defined
    include: _challenge.yml
    vars:
      challenge_yml: "{{item}}"
    with_fileglob:
      - "../challenges/*.yml"
