name: ci-tests

on:
  push:
    paths-ignore:
    - '**.md'
    - '.mkdocs.yml'
    - 'docs/**'
    branches: [ master ]

jobs:
  phpcomposer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure github token
      run: composer config -g github-oauth.github.com "${{ secrets.GITHUBOAUTHTOKEN }}"


    - name: Validate frontend composer.json and composer.lock
      run: |
        cd frontend
        composer validate

    - name: Validate backend composer.json and composer.lock
      run: |
        cd backend
        composer validate


    - name: Install frontend dependencies
      run: |
        cd frontend
        composer install --no-dev --prefer-dist --no-progress --no-suggest

    - name: Install backend dependencies
      run: |
        cd backend
        composer install --no-dev --prefer-dist --no-progress --no-suggest

  dockerbuilds:
    needs: [phpcomposer]
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUBOAUTHTOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Enable experimental docker features
      run: |
        echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart

    - name: Configure github token
      run: composer config -g github-oauth.github.com "${{ secrets.GITHUBOAUTHTOKEN }}"

    - name: Install frontend dependencies
      run: |
        cd frontend
        composer install --no-dev --prefer-dist --no-progress --no-suggest

    - name: Install backend dependencies
      run: |
        cd backend
        composer install --no-dev --prefer-dist --no-progress --no-suggest

    - name: Build the all-in-one Docker image
      run: docker build --squash . --file contrib/Dockerfile --tag echoctf.red-all-in-one:$(date +%s)
    - name: Build the DB Docker image
      run: docker build --squash . --file contrib/Dockerfile-mariadb --tag echoctf.red-db:$(date +%s)
    - name: Build the frontend Docker image
      run: docker build --squash . --file contrib/Dockerfile-frontend --tag echoctf.red-frontend:$(date +%s)
    - name: Build the backend Docker image
      run: docker build --squash . --file contrib/Dockerfile-backend --tag echoctf.red-backend:$(date +%s)
    - name: Build the vpn Docker image
      run: docker build  --squash . --file contrib/Dockerfile-vpn --tag echoctf.red-vpn:$(date +%s)

    - name: Build the docker-compose stack
      run: docker-compose up -d

    - name: Check running containers
      run: docker ps -a

    - name: Drop containers
      run: docker-compose down --rmi all

    - name: Build the docker-compose-novpn.yml stack
      run: docker-compose -f docker-compose-novpn.yml up -d

    - name: Check running containers
      run: docker ps -a

    - name: Drop containers
      run: docker-compose down --rmi all

  dockerhub:
    needs: [dockerbuilds]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure github token
      run: composer config -g github-oauth.github.com "${{ secrets.GITHUBOAUTHTOKEN }}"

    - name: Install frontend dependencies
      run: |
        cd frontend
        composer install --no-dev --prefer-dist --no-progress --no-suggest

    - name: Install backend dependencies
      run: |
        cd backend
        composer install --no-dev --prefer-dist --no-progress --no-suggest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: echothrust/echoctf.red-all-in-one:latest
        context: .
        file: contrib/Dockerfile
        platforms: linux/amd64

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: echothrust/echoctf.red-db:latest
        context: .
        file: contrib/Dockerfile-mariadb
        platforms: linux/amd64

    - uses: docker/build-push-action@v2
      with:
        tags: echothrust/echoctf.red-frontend:latest
        push: true
        context: .
        file: contrib/Dockerfile-frontend
        platforms: linux/amd64

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: echothrust/echoctf.red-backend:latest
        context: .
        file: contrib/Dockerfile-backend
        platforms: linux/amd64

    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: echothrust/echoctf.red-vpn:latest
        context: .
        file: contrib/Dockerfile-vpn
        platforms: linux/amd64
